articles/urls.py
from django.urls import include, path

from articles.views import (
    article_search_view,
    article_create_view,
    article_detail_view
)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),

]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from search.views import search_view
from .views import home_view

from meals.views import meal_queue_toggle_view

urlpatterns = [
    path('', home_view),
    path('pantry/recipes/', include('recepies.urls')),
    path('articles/', include('articles.urls')),
    path('meal-toggle/<int:recipe_id>', meal_queue_toggle_view, name='meal-toggle'),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

        <script src="https://unpkg.com/htmx.org@1.9.2"></script>
        <link rel="stylesheet" href="{% static 'recipes/recipes-htmx.css' %}"/>
    </head>
    <body>
        
        {% include 'base/navbar.html' %}

        <div class="container-fluid">

            {% block content %}
            {% endblock content %}

        </div>


        <!-- Option 1: Bootstrap Bundle with Popper -->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

        <script>
            document.body.addEventListener("htmx:configRequest", (event)=>{
                event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}'
            })
        </script>

    </body>
</html>

templates/home-view.html
{% extends "base.html" %}

{% block content %}
<h1>{{ title }} (id: {{ id }})!</h1>
<p>{{ content }}!</p>

<a href="{% url 'articles:create' %}">Create Article</a>
<h2>More articles:</h2>
<ul>
    {% for article in articles_list %}
        {% if article.title %}
            <li><a href='{{ article.get_absolute_url }}'>{{ article.title}}</a></li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock content %}

templates/image-form.html
{% extends "base.html" %}


    {% block content %}

    <form action="." method="POST" enctype="multipart/form-data" hx-post="{{ request.path }}" hx-encoding="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button style="margin-top:10px; type="submit">Upload Image</button>
    </form>

    {% endblock content %}