articles/urls.py
from django.urls import include, path

from articles.views import (
    article_search_view,
    article_create_view,
    article_detail_view
)

app_name = 'articles'
urlpatterns = [
    path('', article_search_view, name='search'),
    path('create/', article_create_view, name='create'),
    path('<slug:slug>/', article_detail_view, name='detail'),

]

recepies/urls.py
from django.urls import path
from django.urls import reverse

from .views import (
    recipe_list_view,
    recipe_detail_view,
    recipe_delete_view,
    recipe_create_view,
    recipe_update_view,
    recipe_detail_hx_view,
    recipe_ingredient_update_hx_view,
    recipe_ingredient_delete_view,
    recipe_ingredient_image_upload_view
)


app_name = "recipes"
urlpatterns = [
    path("", recipe_list_view, name="list"),
    path("create/", recipe_create_view, name="create"),

    path("hx/<int:parent_id>/ingredient/<int:id>/", recipe_ingredient_update_hx_view, name="hx-ingredient-detail"),
    path("hx/<int:parent_id>/ingredient/", recipe_ingredient_update_hx_view, name="hx-ingredient-create"),
    path("hx/<int:id>/", recipe_detail_hx_view, name="hx-detail"),

    path("<int:parent_id>/image-upload/", recipe_ingredient_image_upload_view, name='recipe-ingredient-image-upload'),
    path("<int:parent_id>/ingredient/<int:id>/delete/", recipe_ingredient_delete_view, name="ingredient-delete"),
    path("<int:id>/delete/", recipe_delete_view, name="delete"),
    path("<int:id>/edit/", recipe_update_view, name="edit"),
    path("<int:id>/", recipe_detail_view, name="detail"),

]

trydjango/urls.py
from django.contrib import admin
from django.urls import include, path

from accounts.views import (
    login_view,
    logout_view,
    register_view
)
from search.views import search_view
from .views import home_view

from meals.views import meal_queue_toggle_view

urlpatterns = [
    path('', home_view),
    path('pantry/recipes/', include('recepies.urls')),
    path('articles/', include('articles.urls')),
    path('meal-toggle/<int:recipe_id>', meal_queue_toggle_view, name='meal-toggle'),
    path('search/', search_view, name='search'),
    path('admin/', admin.site.urls),
    path('login/', login_view),
    path('logout/', logout_view),
    path('register/', register_view),
]

templates/recipes/create-update.html
{% extends "base.html" %}

{% block content %}
<style>
    .ingredient-form {
        border-bottom: 1px solid black;
        border-top: 1px solid black;
    }
    .hidden {
        display: none
    }
</style>


<div class="row" >
    <div class="{% if object.id %} col-12 col-md-8 {% else %} col-md-6 mx-auto{% endif %}">
        {% if not object.id %}
            <h1>Create recipe</h1>
        {% endif %}
        {% include 'recipes/partials/forms.html' %}
    </div>

    <div class="{% if object.id %} col-12 col-md-4 {% else %} d-none {% endif %}">
        <h3>Ingredients</h3>
        {% for ingredient in object.get_ingredients_children %}
            {% include 'recipes/partials/ingredient-inline.html' with object=ingredient %}
        {% endfor %}
        {% if new_ingredient_url %}
        <div hx-get="{{ object.get_image_upload_url }}" hx-trigger='revealed'>

        </div>

        <div id="ingredient-create">
            
        </div>
        
        <button hx-get="{{ new_ingredient_url }}" hx-trigger="click" hx-target="#ingredient-create" hx-swap="beforeend">Add ingredient</button>
        {% endif %}
    </div>
</div> 


<script>
    
    // run event listener on document
    document.addEventListener("click", (event)=> {
        if (event.target.id == "add-more") {
            add_new_form(event)
        }
    })
    function add_new_form(event) {
        if (event) {
            event.preventDefault()
        } 
        const totalNewForms = document.getElementById("id_form-TOTAL_FORMS")
        const currentIngredientForms = document.getElementsByClassName("ingredient-form")
        const currentFormCount = currentIngredientForms.length //+ 1
        const formCopyTarget = document.getElementById("ingredient-form-list")
        const copyEmptyFormEl = document.getElementById("empty-form").cloneNode(true)
        copyEmptyFormEl.setAttribute("class", "ingredient-form")
        copyEmptyFormEl.setAttribute("id", `form-${currentFormCount}`)
        const regex = new RegExp("__prefix__", "g")
        copyEmptyFormEl.innerHTML = copyEmptyFormEl.innerHTML.replace(regex, currentFormCount)
        totalNewForms.setAttribute("value", currentFormCount +1)
        // add new empty form element
        formCopyTarget.append(copyEmptyFormEl)

    }
</script>


{% endblock content %}

templates/recipes/delete.html
{% extends "base.html" %}


{% block content %}

{% if object %}
    <form method="POST" action=".">
        {% csrf_token %}
        <p> Delete {{ object.title }}?</p>
        <button type="submit">Delete</button>
    </form>
    
{% endif %}

{% endblock content %}

templates/recipes/detail.html
{% extends "base.html" %}


{% block content %}

<div hx-get="{{ hx_url }}" hx-trigger="revealed">
    <div class="htmx-indicator">Loading...</div>
</div>

{% endblock content %}

templates/recipes/list.html
{% extends "base.html" %}

{% block content %}
<h1>My Recipes!</h1>

<h2><a href="{% url 'recipes:create' %}">Create Recipe</a></h2>
<hr/>
<h2>More recipes:</h2>
{% for recipe in object_list %}
    {% if recipe.name %}
        <div class="mb-3">
            <a class="lead" href='{{ recipe.get_absolute_url }}'>{{ recipe.name }}</a>
            <div hx-get='{% url "meal-toggle" recipe_id=recipe.id %}' hx-trigger="revealed"></div>
        </div>
    {% endif %}
{% endfor %}
{% endblock content %}

templates/recipes/upload-image.html
{% extends "base.html" %}


    {% block content %}

    {% include 'recipes/partials/image-upload-form.html' %}

    {% endblock content %}